#!/bin/bash


__minecraftctl_register_completions() {
    local USER_INPUT PREV_CMD CMD_LIST COMPGENSCRIPT_PATH
    USER_INPUT="${COMP_WORDS[COMP_CWORD]}"
    PREV_CMD="${COMP_WORDS[COMP_CWORD-1]}"
    COMPGENSCRIPT_PATH=`cat $MINECRAFTCTL_CONF_FILE | grep 'MINECRAFTCTL_COMPGENPATH=' | sed 's/MINECRAFTCTL_COMPGENPATH=//g'`
    if [ "$PREV_CMD" == "minecraftctl" ]; then
        CMD_LIST=`cat ${COMPGENSCRIPT_PATH}/commands | sed 's/\n/\ /g'`
    else
        if [ -f ${COMPGENSCRIPT_PATH}/prompt.d/$PREV_CMD ]; then
            # TODO: add parameter for compgen
            source ${COMPGENSCRIPT_PATH}/prompt.d/$PREV_CMD
            CMD_LIST=$($PREV_CMD ${COMPGENSCRIPT_PATH})
        else
            CMD_LIST=""
        fi
    fi
    COMPREPLY=($(compgen -W "$CMD_LIST" -- "$USER_INPUT"))
}

complete -F __minecraftctl_register_completions minecraftctl

