
services:
    bluemap:
        image: ${MCMAP_IMAGE}:${MCMAP_IMAGE_VERSION}
        container_name: ${SERVER_NAME}_mcmap
        restart: always
        command: -r -u -w
        networks:
            - mcmap_net
        volumes:
            - ${MCMAP_WEB_DIR}:/app/config
            - ${MCWORLD}:/app/world:ro
            - ${MCMAP_WEB_DIR}:/app/data
            - ${MCMAP_WEB_DIR}:/app/web

networks:
    mcmap_net:
        external: true
        name: "mcmap_net"

