
services:
    mcmap_proxy:
        image: nginx:latest
        container_name: mcmap_proxy_server
        restart: always
        networks:
            - mcmap_net
        volume:
            - {MAP_LOCATION_CONF}:/etc/nginx/conf.d/locations

networks:
    mcmap_net:
        external: true
        name: "mcmap_net"

